## Intro to Pytorch

In [1]:
import torch

In [2]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

#### .device gives which device the current exeuction is on. To move a tensor to a new device, you can write new_tensor = example_tensor.to(device) where device will be either cpu or cuda

In [5]:
example_tensor.device

device(type='cpu')

In [6]:
example_tensor.shape

torch.Size([3, 2, 2])

##### You can also get the size of a particular dimension n using example_tensor.shape[n] or equivalently example_tensor.size(n)

In [9]:
print("shape[0] =", example_tensor.shape[0])
print("size(1) =", example_tensor.size(1))

shape[0] = 3
size(1) = 2


In [10]:
print("Rank =", len(example_tensor.shape))
print("Number of elements =", example_tensor.numel())

Rank = 3
Number of elements = 12


### Indexing Tensors

In [11]:
example_tensor[1]

tensor([[5., 6.],
        [7., 8.]])

In [13]:
example_tensor[1, 1, 0]

tensor(7.)

#### item() can be used to get scalar output. It cant give array output

In [16]:
example_tensor[1].item()

ValueError: only one element tensors can be converted to Python scalars

In [17]:
example_tensor[1, 1, 0].item()

7.0

In [18]:
example_tensor[:, 0, 0]

tensor([1., 5., 9.])

### Initializing Tensors

In [19]:
torch.ones_like(example_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [20]:
torch.zeros_like(example_tensor)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [22]:
torch.ones([1,2])

tensor([[1., 1.]])

In [23]:
torch.rand([1,2,3])

tensor([[[0.5455, 0.3661, 0.7834],
         [0.3422, 0.7406, 0.4084]]])

In [24]:
torch.randn_like(example_tensor)

tensor([[[-1.5426,  0.9418],
         [-0.1294, -1.2423]],

        [[-1.5872,  0.6830],
         [-2.3797, -1.0744]],

        [[-0.5091, -1.5454],
         [-1.2645,  0.5356]]])

#### assigning device to a tensor. 'cpu' and 'cuda'

In [25]:
torch.randn(2, 2, device='cpu')

tensor([[ 0.8111, -0.0975],
        [ 0.6630,  0.3605]])

In [26]:
torch.randn(2, 2, device='cuda')

tensor([[-0.5949,  1.2121],
        [-0.0271, -0.5514]], device='cuda:0')

In [27]:
torch.randn(2, 2, device='gpu')

RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mlc, xla, lazy, vulkan, meta, hpu device type at start of device string: gpu

### Basic functions

In [29]:
(example_tensor - 5) * 2

tensor([[[ -8.,  -6.],
         [ -4.,  -2.]],

        [[  0.,   2.],
         [  4.,   6.]],

        [[  8., -10.],
         [ -8.,  -6.]]])

In [30]:
print("Mean:", example_tensor.mean())
print("Stdev:", example_tensor.std())

Mean: tensor(4.)
Stdev: tensor(2.9848)


In [32]:
example_tensor.mean(0)
# Equivalently, you could also write:
# example_tensor.mean(dim=0)
# example_tensor.mean(axis=0)
# torch.mean(example_tensor, 0)
# torch.mean(example_tensor, dim=0)
# torch.mean(example_tensor, axis=0)

tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])